<p>This is About Valencia page. Outside of playing video games, she loves writing stories, reading books and watching puppy videos. Below is a few pictures of their favorite animals</p>
<a href="/Assignment 1/german-shepard-puppy-cross-stitch.html"><img src="Assignment 1/gspuppy.jpg" width="200" height="200" "></a>
<a href="/Assignment 1/golden-retriever.html"><img src="Assignment 1/grpuppy.jpg" width="200" height="200" "></a>
<a href="/Assignment 1/husky.html"><img src="Assignment 1/husky.jpg" width="200" height="200" "></a>