<!DOCTYPE html>
<html>
<body>

<p>My  personal list of her favorite video game series </p>
<img  id='home' src='/Assignment 1/assassin_s_creed_syndicate_pc.jpg' width='200px' height ='200px' >
<h4>Assassin's Creed</h4>
<p>Assassin's Creed is a popular video game series by Ubisoft.It is about a group called the Assassins as they take out the  corruption in their various towns and cities. The game takes place in various historical time periods. I love this game because it promotes rebelling against corruptted power and overthrowing dictators. </p>
<img id='home' src='/Assignment 1/220px-Mafia_III_cover_art.jpg' width='200px' height ='200px' >
<h4>Mafia </h4>
<p>The Mafia series is a series created by 2K. Each game is about the main character getting involved with the mafia and how their live changed after joining. I enjoy this game for it's amazing storytelling.   </p>
<img id='home' src='/Assignment 1/borderlands.jpg' width='200px' height ='200px'>
<h4>Borderlands</h4>
<p>Borderlands is a first-person shooter role-playing game created by 2k. The game is about a group of vault hunter finding treasure on various planets. I enjoy this game because of it's fast pace gameplay. </p>
</body>
</html>